### ISSUE TITLE
Think of better name than HabitCoach

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/HabitsuV2#2]

**Comment by paulmthiebauth** [comment]
Habitsu Junior

**Comment by paulmthiebauth** [comment]
Habitsu: Reloaded

**Comment by paulmthiebauth** [comment]
Habitsu: Part Deux

**Comment by paulmthiebauth** [comment]
Jugo.Futbol

**Comment by SpencerCDixon** [comment]
Dude habitsu is sick, we could just use that and expand on it... thoughts?  the internals of the rails app is alittle messed up though ahha

**Comment by SpencerCDixon** [comment]
how hard would it be for you to transfer over all the front end stuff if we re-did the back end?
