### ISSUE TITLE
How to download your  video ?

### ISSUE THREAD

**Issue by collegeimprovements** [SpencerCDixon/HabitsuV2#20]
I'm learning web-dev from [your live-coding video](https://www.livecoding.tv/video/habitsu-rails-4-vim-rspec-capybara-99//)
but there doesn't seem any option to `download` the video! 
How can I do that?

**Comment by SpencerCDixon** [comment]
Dont know unfortunately sorry!

**Comment by collegeimprovements** [comment]
No Problem. Thanks for your reply :)
